### ISSUE TITLE
Can't create avtomated build

### ISSUE THREAD

**Issue by vukor** [docker/hub-beta-feedback#135]
When i pushed "Create Avtomated Build" and selected, for example, my repo "docker-lnmp" i got the warning "Invalid Docker Hub repository name No spaces and special characters other than - and . are allowed. Repo names should not begin/end with a . or - ."
But the name "docker-lnmp" is correct, isn't it?

**Comment by ChristopherBiscardi** [comment]
I successfully created a normal repo with the name `docker-lnmp` and I was also able to reproduce the bug when creating an Automated Build. So this is scoped to being a bug with the Automated Build creation I think.

`docker-lnmp` is a valid repo name.

ping @rrarunan

**Comment by vukor** [comment]
I share screenshot https://www.evernote.com/shard/s482/sh/1999afb4-4835-4f38-99f4-84b0a82b2fd8/e4c6931fa16675f247c051735c6684e9/deep/0/Docker-Hub.png

what am I doing wrong?

**Comment by rrarunan** [comment]
@vukor Its a bug on our side. Looking into it.

**Comment by jakirkham** [comment]
+1

**Comment by jakirkham** [comment]
Any chance this will be fixed before the roll out?

**Comment by rrarunan** [comment]
I was able to create an autobuild with a `hyphen` in there. `https://hub-beta.docker.com/r/rrarunan/dotanode-lnmp/`. @jakirkham @vukor Can you please verify if its working now and close. Thanks!

**Comment by jakirkham** [comment]
I tried to do this with a fork of @vukor's repo. Unfortunately, it won't let me create it. I don't know if that is because it is a fork or because of the dash. If I look at the console, I get the following error...

    {"detail": "You do not have permission to perform this action."}

**Comment by jakirkham** [comment]
Weird. I logged out and logged back in and was able to create it fine. Not sure what that error was about. It now seems to work.

**Comment by jakirkham** [comment]
@rrarunan, this appears to work for me. I was able to create an automated build and run a build to completion. @vukor, thoughts?

**Comment by vukor** [comment]
@jakirkham, unfortunately, i got same error "Invalid Docker Hub repository name No spaces and special characters other than - and . are allowed. Repo names should not begin/end with a . or - ." 

I tried:
  - log in/ log out 2-3 times on hub
  - Create Automated Build for different repo: docker-lnmp, docker-vlc, docker-guidebook

**Comment by ChristopherBiscardi** [comment]
@vukor I was able to create a repo named `docker-lnmp` from a github repo on hub.docker.com.

Additionally I was able to reproduce the bug by trying to create an Automated Build with *the same name* as another repo.

@rrarunan We just need to update the error message to reflect the potential for a repo that already exists.

```
{"dockerhub_repo_name": ["Invalid Docker Hub repository name"]}
```

^ is all we get from the API in this scenario, so we'll have to just expand the error message to include repos with the same name. In the future maybe we can be smarter about the detection on the client-side.

**Comment by vukor** [comment]
@ChristopherBiscardi 
So, now i successfully create AB (Avtomated Build) for docker-lnmp, but named AB as "docker"
I think, this is not normal situation. For example, in "Repo info" i see string "docker pull vukor/docker", but i don't have this image :)

Thanks for help.

p.s. where i can found listing of all created AB?

**Comment by ChristopherBiscardi** [comment]
@vukor you would be able to see your automated builds (and repos in general) on your dashboard.

**Comment by ChristopherBiscardi** [comment]
Since the Automated Build issue seems to be fixed I'm going to close this issue. Feel free to reopen if the issue persists.

**Comment by AdieSutcliffe** [comment]
I don't see this fixed.  Am brand new to Docker Hub today and am trying to create an AB for a github repo and am experiencing this very problem.

Now being new to this I might be doing something wrong, however I tried to create an AB for a github repo with hyphens in the name and was presented with the error message.  I then changed the name within the AB to have zero non alpha chars and still received the error message.  I then logged out, went to GitHub and renamed the repo to have zero non alpha chars, logged back into Docker Hub and upon trying to create an AB still received the error message.

**Comment by rrarunan** [comment]
@AdieSutcliffe can you please tell us what name you tried to create the autobuild with, so we can help you further?

**Comment by AdieSutcliffe** [comment]
Hi,

Yes I'm trying to base the build on a GiHub repo named PluralsightDockerCI and am naming the build the same.  Hopefully the screenshot will have attached.

I also tried with a GitHub repo named EMC and again the create build page failed with the same message.

As an aside, I also experience a quirk typing into either the Name or Description text boxes, in that if I have the caret midway through a work as soon as I type a character the caret jumps to the end of the all of the text in the box.

![image](https://cloud.githubusercontent.com/assets/8449541/10422821/95f0740a-70b7-11e5-80fe-78dc666a2176.png)

**Comment by wikier** [comment]
Not working for me either:

![docker-hub-issue-135](https://cloud.githubusercontent.com/assets/812223/11299204/000f14e0-8f85-11e5-8f67-2066d6493492.png)

    Remote Address: 52.3.64.1:443
    Request URL: https://hub.docker.com/v2/repositories/undefined/docker-base-dev/autobuild/
    Request Method: POST
    Status Code: 403 FORBIDDEN
    {"detail": "You do not have permission to perform this action."}

Where that `undefined` in the URL comes from?

**Comment by pravindahal** [comment]
@wikier Did you manage to resolve it? I am getting the same error.

**Comment by 3stadt** [comment]
For someone having the same problem, I just solved it:

The generated URL had the wrong format. Use this format:

https://hub.docker.com/add/automated-build/github/form/<GITHUB USER ID>/<GITHUB REPO NAME>/?namespace=<DOCKERHUB NAMESPACE>

Where DOCKERHUB NAMESPACE is your username on dockerhub. For some reason it was "github" in my case, therefore the 403.

**Comment by thompsnm** [comment]
Thanks @3stadt !

I was having the exact same problem, as were a few people in [this forum thread](https://forums.docker.com/t/automated-build-never-builds/18713/16), and your solution worked for me.

**Comment by qwIvan** [comment]
Thanks for @3stadt !
resolved in my case.

**Comment by vyscond** [comment]
👍  for the @3stadt explanation and fix! thanks a bunch dude.

**Comment by ndarilek** [comment]
Had this exact same issue. Surprised it isn't fixed.

Am I expected to manually send a POST request to the URL above? I thought this sort of thing would be totally ironed out on Docker's flagship platform. Figured it'd be easier than spinning up my own CI job to build and push a custom image.

Thanks.
